version: '0.1.0'

services:
  database:
    container_name: catalog_db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mongoCatalogData:/var/lib/mongodb/data

volumes:
  mongoCatalogData:
