version: '0.1.0'

services:
  database:
    container_name: catalog_db
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - pgCatalogData:/var/lib/postgresql/data

  volumes:
    pgCatalogData:
